# -*- coding: utf-8 -*-
import io
import scratch_read_ffj_sheet as s

bodies = {
42: "Rascarse más de la cuenta, pelo sin brillo, piel tirante… no es capricho de su pelaje, es una señal. El pienso se procesa a más de 150°C, una temperatura que destruye gran parte de los ácidos grasos esenciales que su piel necesita para mantenerse hidratada. Sin ellos, la piel se reseca y el pelo pierde fuerza y brillo. La comida cocinada a baja temperatura con ingredientes reales conserva esas grasas intactas, justo lo que su piel y su pelo llevan tiempo pidiendo.",
43: "El pelo y la piel son el primer aviso, mucho antes de que aparezca un problema más serio. Cuando el pienso se procesa a altas temperaturas, pierde buena parte de las vitaminas y los ácidos grasos que la piel necesita para regenerarse cada día. El resultado se ve por fuera: pelo apagado, caída excesiva, piel reseca. La comida cocinada con ingredientes frescos mantiene esos nutrientes intactos, y la mayoría de dueños empieza a notar el cambio en cuestión de semanas.",
44: "Este es el pelo del mismo gato, tres semanas después de dejar el pienso. Nada de productos milagro: solo proteína de calidad y ácidos grasos que su cuerpo por fin puede aprovechar. Con comida cocinada a baja temperatura y con ingredientes reales, el folículo recibe lo que necesita para regenerar un pelo más denso y brillante, algo que el pienso ultraprocesado apenas le aportaba.",
45: "Gasté meses en champús especiales, cepillos de todo tipo y suplementos, convencida de que el problema estaba en el pelo de mi gato. Hasta que un día le di la vuelta al saco de pienso: harinas de subproductos, cereales de relleno, aditivos que ni sabía pronunciar. El pelo no se arregla por fuera si por dentro no le llega lo que necesita. Desde que cambié a comida cocinada con ingredientes reales, no he vuelto a tocar un champú especial.",
46: "Encontrar pelo de tu gato en cada rincón de casa puede parecer normal, pero la caída excesiva casi siempre tiene una causa: el pienso procesado a altas temperaturas apenas conserva las proteínas y los ácidos grasos que el folículo necesita para mantener el pelo sujeto y fuerte. La comida cocinada con ingredientes reales devuelve esos nutrientes a su dieta, y con ellos, un pelo que cae menos y se ve más sano.",
47: "Sabes que lo ideal sería cocinarle tú mismo, con ingredientes frescos y en las cantidades justas. Pero entre el trabajo, la casa y las mil cosas del día, ese tiempo no existe. Y aunque lo tuvieras, calcular una dieta felina completa —proteína, taurina, vitaminas, minerales— no es tarea sencilla sin formación en nutrición. Food for Joe cocina por ti con ingredientes reales como pollo o pescado, a baja temperatura y con recetas formuladas por veterinarios. Tú solo abres, sirves y ya está.",
48: "Muchos dueños sueñan con darle comida casera a su gato, pero entre calcular proporciones y encontrar tiempo para cocinar cada día, el proyecto se queda en eso: un sueño. Con Food for Joe tienes el mismo resultado sin el esfuerzo. Recetas cocinadas con ingredientes reales, formuladas por veterinarios nutricionistas y entregadas en raciones individuales listas para servir. Como si lo hubieras cocinado tú, pero sin encender el fuego.",
49: "Probé prácticamente todas las marcas del supermercado y mi gato dejaba el plato a medias, siempre. Pensé que simplemente era exigente. Hasta que probé una comida cocinada con ingredientes reales: el olor, la textura, todo cambió. La primera vez que vació el plato entero pensé que se había equivocado de gato.",
50: "Los gatos comen primero con la nariz. Si el olor de su comida no les convence, ni se acercan al plato, por muy bueno que sea el pienso sobre el papel. El proceso de fabricación a altas temperaturas hace que el pienso pierda buena parte de su aroma natural. La comida cocinada con ingredientes reales conserva ese olor que un gato reconoce al instante como comida de verdad, y eso se nota ya en el primer plato.",
51: "Cuando un gato rechaza comida nueva, no es un capricho: es instinto de supervivencia guiado casi por completo por el olfato. Si algo no huele a lo que su cuerpo reconoce como comida, lo rechaza sin pensarlo dos veces. El pienso procesado a altas temperaturas pierde gran parte de ese aroma natural. La comida cocinada con ingredientes reales conserva ese olor auténtico que su instinto sí identifica como alimento.",
52: "Cambiar de marca a ciegas, sin saber si tu gato la va a aceptar, es tirar el dinero y la paciencia. La clave está en el olfato: un gato identifica comida real por su olor, algo que el pienso pierde en gran parte durante el procesado. Al cocinar con ingredientes reales como pollo o pescado, Food for Joe conserva ese aroma natural que dispara la aceptación desde el primer bocado.",
53: "Un plato a medias no siempre es cuestión de cantidad: muchas veces es que lo que hay dentro no le resulta apetecible. El procesado a altas temperaturas del pienso apaga buena parte de su aroma natural. La comida cocinada con ingredientes reales conserva ese olor y esa textura que un gato reconoce de verdad como comida, y eso se traduce en platos vacíos.",
54: "Servir \"a ojo\" es de los errores más comunes, y también de los que más rápido pasan factura: sobrepeso si te pasas, carencias si te quedas corto. Cada gato necesita una ración calculada según su peso, su edad y su actividad, no un puñado estimado. Con Food for Joe no calculas nada: nos cuentas cómo es tu gato y te llegan las raciones exactas, ya pesadas y listas para servir.",
55: "El sobrepeso casi nunca es solo \"comer demasiado\": muchas veces el problema son las raciones calculadas a ojo, sin ajustar a su peso real. A eso se suma que el pienso está cargado de carbohidratos de relleno que su cuerpo no necesita y termina almacenando como grasa. Food for Joe calcula la ración exacta de tu gato con ingredientes reales, sin relleno de por medio.",
56: "Rellenar el comedero varias veces al día hace muy fácil perder la cuenta de cuánto come tu gato realmente. Y el pienso, al concentrar muchas calorías en poco volumen, no ayuda: es fácil pasarse sin darte cuenta. Con Food for Joe cada ración llega ya calculada según su peso, su edad y su actividad. No tienes que adivinar nada, solo servir.",
57: "¿Puede algo \"natural\" y sin aditivos cubrir de verdad lo que necesita un carnívoro estricto como tu gato? Es la duda más razonable que existe. La respuesta está en la formulación: cada receta de Food for Joe la diseñan veterinarios nutricionistas siguiendo el estándar FEDIAF, con las cantidades exactas de proteína, taurina, vitaminas y minerales que su cuerpo necesita. Natural, sí. Improvisado, nunca.",
58: "Natural no garantiza completo si detrás no hay una formulación seria, y esa es la duda que frena a muchos dueños. La diferencia con Food for Joe está en quién diseña cada receta: veterinarios nutricionistas que siguen el estándar FEDIAF, calculando taurina, proteína, vitaminas y minerales en las proporciones exactas. Nutrición completa y verificada, no solo ingredientes que le gustan.",
59: "Un gato es carnívoro estricto, con necesidades muy concretas de proteína animal y nutrientes como la taurina que no se pueden improvisar. Formular una dieta natural sin ese conocimiento puede pasar factura a largo plazo, aunque no se note al principio. Cada receta de Food for Joe la desarrollan veterinarios nutricionistas siguiendo el estándar FEDIAF, calculando exactamente lo que tu gato necesita según su peso y su edad.",
60: "El miedo a que \"le falte algo\" tiene sentido: las necesidades nutricionales de un gato son muy concretas, y una dieta mal formulada puede generar carencias silenciosas que solo se notan cuando ya es tarde. Con Food for Joe no se deja nada al azar: recetas formuladas por veterinarios nutricionistas siguiendo el estándar FEDIAF, con las cantidades exactas que su cuerpo necesita.",
61: "Cambiar la comida de golpe casi siempre sale mal con un gato: rechazo, vómitos, diarreas. La clave está en ir despacio, mezclando una pequeña cantidad de la comida nueva con la habitual y aumentando la proporción poco a poco durante varios días. Con Food for Joe además te acompañamos en cada paso, indicándote las cantidades exactas para que la transición sea lo más suave posible.",
62: "El miedo al rechazo frena a muchos dueños que querrían cambiar la comida de su gato pero no se atreven. Y tiene sentido: los gatos son especialmente selectivos, y un cambio brusco puede terminar mal. Por eso el proceso se hace de forma gradual, con pequeñas cantidades cada día. Y la textura y el olor de la comida cocinada con ingredientes reales suele ganarse su aceptación desde el primer plato.",
63: "Sabemos que un gato odia que le cambien las reglas de golpe, y que un cambio brusco de comida puede acabar en rechazo o malestar digestivo. Por eso en Food for Joe diseñamos un plan de transición gradual, aumentando la proporción cada día hasta que su estómago se adapta por completo, con nuestro equipo acompañándote en cada paso.",
64: "El pienso nació como una forma barata de aprovechar los subproductos que sobraban de la industria alimentaria humana, no pensando en la nutrición óptima de un gato. Se cocina a temperaturas que destruyen buena parte de sus nutrientes naturales, y luego se compensa con aditivos y conservantes. La comida cocinada con ingredientes reales como pollo, pescado o verduras nace justo al revés: pensada desde cero para su salud, no para abaratar costes.",
65: "Durante años le di pienso sin pensarlo demasiado, porque era lo que hacía todo el mundo. Hasta que un día leí de verdad la etiqueta: harinas de subproductos, cereales de relleno, conservantes que ni sabía pronunciar. Desde que cambié a comida cocinada con ingredientes reales, dejé de sentir esa culpa cada vez que le llenaba el plato.",
66: "Las heces son uno de los indicadores más fiables de cómo digiere tu gato lo que come. Blandas, con mal olor o muy voluminosas: suelen ser la señal de que su cuerpo está esforzándose por procesar ingredientes de baja calidad, como las harinas de relleno del pienso. La comida cocinada con ingredientes reales se digiere mejor y de forma más completa, y eso se nota en heces más firmes, pequeñas y con menos olor.",
67: "Si las heces de tu gato cambian de aspecto con frecuencia, son blandas o demasiado voluminosas, es una señal de que algo no se está digiriendo bien. El pienso está cargado de cereales y harinas de relleno que su sistema digestivo procesa con esfuerzo. Con una comida cocinada a base de ingredientes reales, la digestión es más eficiente y las heces suelen normalizarse en cuestión de días.",
68: "Un olor demasiado fuerte en las heces suele significar que el intestino está fermentando ingredientes que no digiere bien, como las harinas de subproductos y los cereales de relleno típicos del pienso. Cuando la digestión es más completa y eficiente, como ocurre con ingredientes reales cocinados a baja temperatura, ese olor se reduce de forma notable.",
69: "Los gatos descienden de animales del desierto, y por instinto apenas sienten la necesidad de beber agua del bebedero. El pienso seco apenas tiene un 10% de humedad, lo que obliga a sus riñones a trabajar con muy poca agua disponible cada día, un desgaste silencioso que se acumula con los años. La comida cocinada contiene más del 70% de humedad natural: tu gato se hidrata simplemente comiendo, sin depender de que beba más.",
70: "Que tu gato apenas toque el bebedero es más habitual de lo que parece: por instinto, obtenían la mayor parte de su hidratación de sus presas, no del agua directa. El problema es que el pienso seco, con apenas un 10% de humedad, no compensa esa falta de ingesta, exigiendo un esfuerzo extra a sus riñones con el paso de los años. La comida cocinada aporta más del 70% de humedad natural: se hidrata mientras come.",
71: "A simple vista, un pienso barato y una comida natural parecen cumplir la misma función, así que la duda sobre si merece la pena pagar más es totalmente razonable. La diferencia está en lo que hay detrás de cada bocado: ingredientes reales frente a harinas de relleno, una digestión más eficiente y menos problemas de salud con el tiempo. Ese euro de más al día suele traducirse en menos visitas al veterinario y más años a su lado.",
72: "El precio de la comida natural genera dudas porque el beneficio no siempre se ve a simple vista, y es normal preguntarse si de verdad se nota. Pero la diferencia está en cómo se digiere, en la energía que aporta y en cómo su cuerpo aprovecha cada nutriente, frente a un pienso lleno de relleno que apenas procesa. La mayoría de dueños empieza a notar los cambios —mejor pelo, mejores digestiones, más energía— en cuestión de semanas.",
73: "A simple vista, todos los botes de comida para gatos se parecen. La diferencia real está en la etiqueta: un pienso ultraprocesado cargado de harinas de subproductos y cereales de relleno frente a ingredientes reales como pollo o pescado, cocinados a baja temperatura para conservar sus nutrientes. No es pagar más por lo mismo. Es pagar por algo completamente distinto.",
74: "Muchos dueños descartan la comida natural pensando que es solo para quien puede permitírselo. Pero cada plan de Food for Joe se calcula según el peso y las necesidades exactas de tu gato, así que pagas solo por lo que realmente necesita, sin desperdicio. Sumando lo que muchos gatos ahorran en visitas al veterinario, la diferencia real es mucho menor de lo que parece.",
}

rows = sorted(bodies.keys())
assert rows == list(range(42, 75)), "Faltan filas"

values = [[bodies[r]] for r in rows]

body = {
    "valueInputOption": "USER_ENTERED",
    "data": [
        {
            "range": "'VIDEO'!L42:L74",
            "values": values,
        }
    ],
}

result = s.service.spreadsheets().values().batchUpdate(spreadsheetId=s.SHEET_ID, body=body).execute()

with io.open("scratch_rewrite_ffj_gato_bodies_v2_result.txt", "w", encoding="utf-8") as f:
    f.write(str(result))

print("OK - filas actualizadas:", len(values))
