# -*- coding: utf-8 -*-
import io
import scratch_read_ffj_sheet as s

bodies = {
42: "El pelo y la piel de tu gato reflejan directamente lo que come. El pienso seco se procesa a altas temperaturas que destruyen buena parte de los ácidos grasos y nutrientes que su piel necesita para mantenerse hidratada y su pelo para brillar. Lo que le llega es un alimento pobre en esos nutrientes esenciales. La comida cocinada con ingredientes reales conserva esas grasas saludables intactas, aportando lo que su piel y su pelo necesitan para recuperarse desde dentro.",
43: "Antes de que aparezcan problemas más serios, el cuerpo de tu gato ya te está avisando por fuera. Un pelo apagado, quebradizo o una piel reseca suelen ser de los primeros síntomas de que su alimentación no le está aportando lo que necesita. El pienso ultraprocesado apenas conserva los ácidos grasos y las vitaminas que la piel y el pelo requieren para regenerarse. La comida cocinada a baja temperatura con ingredientes frescos mantiene esos nutrientes intactos, y muchos dueños empiezan a notar el cambio en pocas semanas.",
44: "A las 3 semanas de dejar el pienso y pasarse a comida cocinada con ingredientes reales, el pelo empieza a notarse más denso y con más brillo. No es magia: es que su cuerpo por fin recibe las proteínas de calidad y los ácidos grasos que necesita para regenerar el pelo, algo que el pienso procesado a altas temperaturas apenas le aportaba.",
45: "Probé champús, suplementos y cepillados diarios pensando que el problema estaba en el pelo de mi gato. Pero el pelo no se cuida solo por fuera: necesita nutrientes de calidad que vengan de dentro. Cuando revisé lo que llevaba su pienso, vi harinas de subproductos y cereales de relleno, poco que ver con proteína real. Desde que cambié a comida cocinada con ingredientes reales, no he vuelto a necesitar ningún champú especial.",
46: "La caída de pelo excesiva suele achacarse a la muda o al estrés, pero muchas veces el origen está en el bol. El pienso procesado a altas temperaturas pierde gran parte de los ácidos grasos y proteínas de calidad que el folículo necesita para mantener el pelo fuerte. La comida cocinada con ingredientes reales conserva esos nutrientes, aportando lo que su pelo necesita para crecer sano y caer menos.",
47: "Sabes que lo mejor sería prepararle tú la comida, con ingredientes frescos y raciones pensadas para él. Pero entre el trabajo y el día a día no queda tiempo, y hacerlo bien requiere conocimientos de nutrición felina que no todo el mundo tiene. Food for Joe cocina por ti con ingredientes reales como pollo, pescado o verduras, a baja temperatura y con recetas formuladas por veterinarios. Tú solo abres y sirves.",
48: "La comida casera es la opción ideal para muchos dueños, pero cocinar cada día para tu gato, calculando las proporciones exactas de proteína, vitaminas y minerales que necesita, no es sencillo ni rápido. Con Food for Joe tienes el mismo resultado sin el esfuerzo: recetas cocinadas con ingredientes reales, formuladas por veterinarios nutricionistas y entregadas en raciones listas para servir.",
49: "Había probado casi todas las marcas del mercado y mi gato siempre dejaba el plato a medias. Pensé que era simplemente un gato caprichoso. Hasta que probé una comida cocinada con ingredientes reales, con un olor y una textura mucho más parecidos a lo que un gato reconoce como comida de verdad. Desde entonces no deja ni una miga.",
50: "Los gatos son animales de olfato antes que de vista: si el olor de su comida no les resulta apetecible, la rechazan sin más. El pienso seco pierde gran parte de su aroma natural en el proceso de fabricación. La comida cocinada con ingredientes reales conserva ese olor y esa textura que el instinto de tu gato reconoce como comida de verdad, algo que suele notarse ya desde el primer plato.",
51: "Cuando un gato rechaza un alimento nuevo, no es capricho: es su forma natural de protegerse, guiada casi por completo por el olfato. El pienso, al procesarse a altas temperaturas, pierde buena parte de ese olor natural que un gato necesita reconocer como comida real. La comida cocinada con ingredientes frescos conserva ese aroma natural, mucho más cercano a lo que su instinto identifica como alimento.",
52: "Cambiar de marca sin saber si tu gato la va a aceptar es una de las mayores frustraciones para cualquier dueño. La clave está en el olfato: los gatos identifican la comida real por su olor natural, algo que el pienso procesado pierde en gran parte durante la fabricación. Al cocinar con ingredientes reales como pollo o pescado, Food for Joe mantiene ese aroma natural que hace que la aceptación sea mucho mayor.",
53: "Si tu gato deja comida en el plato de forma habitual, puede que el problema no sea la cantidad, sino lo poco apetecible que le resulta lo que le sirves. El pienso pierde gran parte de su aroma natural durante el procesado a altas temperaturas. La comida cocinada con ingredientes reales conserva ese olor y esa textura, mucho más parecidos a lo que un gato reconoce como comida de verdad.",
54: "Servir la comida \"a ojo\" es de los errores más comunes, y también de los que más fácilmente derivan en sobrepeso o carencias nutricionales. Cada gato necesita una ración calculada según su peso, su edad y su nivel de actividad. Con Food for Joe no tienes que calcular nada: nos dices cómo es tu gato y te enviamos las raciones exactas que necesita, ya pesadas y listas para servir.",
55: "El sobrepeso en gatos casi nunca es solo cuestión de \"comer demasiado\": muchas veces el problema es servir raciones calculadas a ojo, sin ajustarlas a su peso real ni a su actividad. El pienso además está cargado de carbohidratos de relleno que su cuerpo no necesita y acaba almacenando como grasa. Food for Joe calcula la ración exacta de tu gato con ingredientes reales y sin relleno, para que coma lo que realmente necesita.",
56: "Es fácil perder la noción de cuánto come realmente tu gato, sobre todo si rellenas el comedero varias veces al día. El pienso, además, concentra muchas calorías en poco volumen, lo que facilita que sin darte cuenta le estés dando de más. Con Food for Joe cada ración viene ya calculada y pesada según su peso, su edad y su actividad, para que no tengas que adivinar nada.",
57: "Es una de las dudas más habituales: si algo \"natural\" y sin aditivos puede realmente cubrir todas las necesidades nutricionales de un gato, que como carnívoro estricto tiene requerimientos muy específicos de proteína, taurina y otros nutrientes. Cada receta de Food for Joe está formulada por veterinarios nutricionistas siguiendo los estándares FEDIAF, con las cantidades exactas que un gato necesita según su peso, edad y actividad. Natural no significa improvisado.",
58: "Natural no es sinónimo de completo si no está bien formulado, y por eso muchos dueños dudan antes de dar el paso. La diferencia con Food for Joe es que cada receta la diseñan veterinarios nutricionistas siguiendo el estándar FEDIAF, con las proporciones exactas de proteína, taurina, vitaminas y minerales que un gato necesita. Ingredientes reales y nutrición completa, verificadas, no solo lo que le gusta.",
59: "Los gatos son carnívoros estrictos, con necesidades muy concretas de proteína animal y nutrientes como la taurina que no se pueden dejar al azar. Formular una dieta natural sin ese conocimiento puede generar carencias a largo plazo. Por eso cada receta de Food for Joe la desarrollan veterinarios nutricionistas siguiendo el estándar FEDIAF, calculando exactamente lo que tu gato necesita según su peso y su edad.",
60: "El miedo a que \"le falte algo\" es totalmente razonable: un gato tiene necesidades nutricionales muy concretas, y una dieta casera mal formulada puede generar carencias sin que lo notes hasta que es tarde. Con Food for Joe no dejas nada al azar: recetas formuladas por veterinarios nutricionistas siguiendo el estándar FEDIAF, con las cantidades exactas de proteína, vitaminas y minerales que tu gato necesita.",
61: "Los gatos son especialmente sensibles a los cambios de comida, y hacerlo de golpe suele terminar en rechazo o problemas digestivos. La clave está en ir mezclando una pequeña cantidad de la nueva comida con la habitual y aumentar la proporción poco a poco durante varios días. Con Food for Joe además te acompañamos en cada paso, indicándote las cantidades exactas para que la transición sea lo más suave posible.",
62: "El miedo al rechazo es de las principales razones por las que muchos dueños no se atreven a cambiar la comida de su gato. Tiene sentido: los gatos son especialmente selectivos y un cambio brusco puede salir mal. Por eso el proceso se hace de forma gradual, mezclando pequeñas cantidades de la nueva comida con la habitual durante varios días. Además, la textura y el olor de la comida cocinada con ingredientes reales suele generar mejor aceptación desde el principio.",
63: "Sabemos que los gatos son animales de costumbres y que un cambio de comida brusco puede generar rechazo o malestar digestivo. Por eso en Food for Joe te guiamos con un plan de transición gradual, mezclando pequeñas cantidades cada día hasta que su estómago se adapta por completo. Nuestro equipo te acompaña en cada paso para que el cambio sea lo más sencillo posible.",
64: "El pienso nació como una forma barata y práctica de aprovechar subproductos de la industria alimentaria humana, no pensando en la nutrición óptima de un gato. Se fabrica a altas temperaturas que destruyen buena parte de sus nutrientes naturales, y luego se compensa con aditivos y conservantes. La comida cocinada con ingredientes reales como pollo, pescado o verduras es justo lo contrario: comida pensada desde cero para su salud, no para ahorrar costes de producción.",
65: "Durante años le di pienso pensando que estaba bien, porque era lo que hacía todo el mundo. Hasta que un día leí de verdad la etiqueta: harinas de subproductos, cereales de relleno, conservantes que ni sabía pronunciar. Desde que cambié a comida cocinada con ingredientes reales, dejé de sentirme culpable cada vez que le llenaba el plato.",
66: "Las heces son uno de los indicadores más claros de cómo está digiriendo tu gato lo que come. Cuando son blandas, tienen mal olor o son muy voluminosas, suele ser señal de que su cuerpo está digiriendo con esfuerzo ingredientes de baja calidad, como las harinas de relleno del pienso. La comida cocinada con ingredientes reales se digiere mejor y de forma más completa, lo que suele notarse en heces más pequeñas, firmes y con menos olor.",
67: "Si las heces de tu gato son blandas, muy voluminosas o cambian de aspecto con frecuencia, puede ser una señal de que su comida no se está digiriendo bien. El pienso contiene cereales y harinas de relleno que su sistema digestivo procesa con dificultad. Con una comida cocinada a base de ingredientes reales, la digestión es más eficiente y las heces suelen normalizarse en poco tiempo.",
68: "Un olor muy fuerte en las heces suele indicar que el intestino está fermentando ingredientes que no digiere bien, como las harinas de subproductos y los cereales de relleno del pienso. Cuando la comida se digiere de forma más completa y eficiente, como ocurre con ingredientes reales cocinados a baja temperatura, ese olor tiende a reducirse de forma notable.",
69: "Los gatos descienden de animales del desierto y por instinto apenas sienten la necesidad de beber agua directamente del bebedero. El pienso seco apenas tiene un 10% de humedad, lo que obliga a sus riñones a trabajar con muy poca agua disponible cada día. La comida cocinada contiene más del 70% de humedad natural, por lo que tu gato se hidrata simplemente comiendo, sin depender de que beba más.",
70: "Que tu gato apenas beba agua es más habitual de lo que parece: por instinto, obtenían la mayor parte de su hidratación de sus presas, no del agua directa. El problema es que el pienso seco, con apenas un 10% de humedad, no compensa esa falta de ingesta de agua, lo que exige más esfuerzo a sus riñones a largo plazo. La comida cocinada tiene más del 70% de humedad natural, así que tu gato se hidrata mientras come.",
71: "Es normal dudarlo: a simple vista, un pienso barato y una comida natural cumplen la misma función. La diferencia está en lo que hay detrás de cada bocado: ingredientes reales frente a harinas de subproductos y relleno, una digestión más eficiente y menos problemas de salud a largo plazo. Pagar un poco más cada día suele traducirse en menos visitas al veterinario y más años de vida a su lado.",
72: "El precio de la comida natural genera dudas porque no siempre se ve el beneficio a simple vista. Pero la diferencia está en cómo se digiere, en la energía que aporta y en cómo su cuerpo aprovecha cada nutriente, frente a un pienso lleno de relleno que su organismo apenas procesa. Muchos dueños empiezan a notar los cambios (mejor pelo, mejores digestiones, más energía) en pocas semanas.",
73: "A simple vista, todos los botes de comida para gatos pueden parecer iguales. La diferencia real está en la etiqueta: un pienso ultraprocesado lleno de harinas de subproductos y cereales de relleno frente a ingredientes reales como pollo o pescado, cocinados a baja temperatura para conservar sus nutrientes. No es pagar más por lo mismo, es pagar por algo completamente distinto.",
74: "Muchos dueños descartan la comida natural pensando que es solo para quien pueda permitírselo. Pero cada plan de Food for Joe se calcula según el peso y las necesidades exactas de tu gato, así que pagas solo por lo que realmente necesita, sin desperdicio. Sumando lo que muchos gatos ahorran en visitas al veterinario, la diferencia real es mucho menor de lo que parece.",
}

rows = sorted(bodies.keys())
assert rows == list(range(42, 75)), "Faltan filas"

values = [[bodies[r]] for r in rows]

body = {
    "valueInputOption": "USER_ENTERED",
    "data": [
        {
            "range": "'VIDEO'!L42:L74",
            "values": values,
        }
    ],
}

result = s.service.spreadsheets().values().batchUpdate(spreadsheetId=s.SHEET_ID, body=body).execute()

with io.open("scratch_write_ffj_gato_bodies_result.txt", "w", encoding="utf-8") as f:
    f.write(str(result))

print("OK - filas actualizadas:", len(values))
